-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.series
(
    id uuid NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    summary character varying(255) COLLATE pg_catalog."default" NOT NULL,
    chapcount integer NOT NULL,
    cover text COLLATE pg_catalog."default" NOT NULL,
    createdat timestamp without time zone NOT NULL,
    updatedat timestamp without time zone NOT NULL,
    seriesstatus character varying(1) COLLATE pg_catalog."default" NOT NULL,
    chaps uuid[],
    adaptation uuid,
    creator uuid NOT NULL,
    novel boolean NOT NULL,
    CONSTRAINT series_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.series
    OWNER to postgres;

GRANT ALL ON TABLE public.series TO anon;

GRANT ALL ON TABLE public.series TO authenticated;

GRANT ALL ON TABLE public.series TO postgres;

GRANT ALL ON TABLE public.series TO service_role;

ALTER TABLE IF EXISTS public.users
    OWNER TO postgres;

ALTER TABLE IF EXISTS public.users
    DISABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.users
  IS '';

REVOKE ALL ON TABLE public.users FROM anon;
REVOKE ALL ON TABLE public.users FROM authenticated;
REVOKE ALL ON TABLE public.users FROM postgres;
REVOKE ALL ON TABLE public.users FROM service_role;
REVOKE ALL ON TABLE public.users FROM supabase_admin;
GRANT ALL ON TABLE public.users TO anon;

GRANT ALL ON TABLE public.users TO authenticated;

GRANT ALL ON TABLE public.users TO postgres;

GRANT ALL ON TABLE public.users TO service_role;
